### PR TITLE
add guidelines for waypoint ordering

### PR DESCRIPTION
**Pull request by dreed1**
This PR adds waypoint ordering guidelines to the SDK docs.

IT LOOKS LIKE THIS:
screen shot 2016-11-10 at 6 07 29 pm

### CODE REVIEW

**Comment by phats24** [comment]
Dan this looks good! there were a few other items on that JIRA ticket. Are you doing those as a separate PR?

**Comment by phats24** [comment]
Actually, I think we need to point out the numbers and ordering of them moreso than the colors. For example...that the numbers change when the order changes AND that they move in the list when the order changes. That should be highlighted as a "mandatory suggestion" and the coloring is a "optional suggestion" (but don't use that wording).  Ha ha!

**Comment by dreed1** [comment]
Updated now with a different approach, pushing a little harder on waypoint ordering than the coloring.

screen shot 2016-11-14 at 3 15 01 pm
screen shot 2016-11-14 at 3 15 11 pm
screen shot 2016-11-14 at 3 15 36 pm

**Comment by dreed1** [comment]
uhhh i think those last screenshots have everything but I made some new ones anyway just to be sure:

screen shot 2016-11-16 at 10 34 47 am
screen shot 2016-11-16 at 10 34 58 am
screen shot 2016-11-16 at 10 35 05 am

**Comment by pcoughran** [comment]
:shipit: !!

**Pull request merged**
